name: run migration in prod environment

on:
  push:
    tags:
      - "v*"
    paths:
      - "alembic/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-infra:
    uses: ./.github/workflows/run-migration.yml
    with:
      env-name: prod
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_SQL_SERVER_NAME: ${{ secrets.AZURE_SQL_SERVER_NAME }}
