on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_RESOURCE_GROUP:
        required: true
      AZURE_SQL_SERVER_NAME:
        required: true
permissions:
  id-token: write
  contents: read

jobs:
  run-migration:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env-name }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Get IP Address
        id: get_ip
        run: |
          echo "ip=$(curl -s ifconfig.me)" >> $GITHUB_OUTPUT

      - name: Add Firewall Rule
        run: |
          az sql server firewall-rule create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --server ${{ secrets.AZURE_SQL_SERVER_NAME }} \
            --name AllowGitHubActionsIP \
            --start-ip-address ${{ steps.get_ip.outputs.ip }} \
            --end-ip-address ${{ steps.get_ip.outputs.ip }} \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install ODBC Driver for SQL Server
        run: |
          # Add Microsoft GPG key and repository
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
          echo "deb [signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/20.04/prod focal main" | sudo tee /etc/apt/sources.list.d/mssql-release.list

          # Update package lists and install ODBC Driver
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run migration
        env:
          APP_ENV: ${{ inputs.env-name }}
        run: |
          poetry run alembic upgrade head

      - name: Remove Firewall Rule
        run: |
          az sql server firewall-rule delete \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --server ${{ secrets.AZURE_SQL_SERVER_NAME }} \
            --name AllowGitHubActionsIP \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
